apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jpct
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jpct
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-jpct
  namespace: christianvogt-tenant
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jpct
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jpct
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:5ec8379d7227be30b92d6aa87767aaa09bfc5004d8ac36c4f5798a9366b3031d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
