apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sv7u
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sv7u
    app.kubernetes.io/part-of: my-app-1
  name: devfile-sample-sv7u
  namespace: christianvogt-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sv7u
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sv7u
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:64556e7fa2d06a6f30d9c308bd4d701bb638766fc35ea2e36dd45c031bc60fc0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
